json.extract! @user, 
        :username,
        :token,
        :token_expiry,
        :status,
	:first_name, 
        :mid_name, 
        :last_name,
        :email,
        :birthday,
        :cellphone_number,
        :telephone_number,
        :address,
        :date_start,
        :created_at
